title Ligth spoofer
start Ligthmapper 1.sys
start Ligthmapper 2.sys
start Ligthmapper 3.sys
start Ligthmapper 4.sys
start Ligthmapper 5.sys
start Ligthmapper 6.sys
start Ligthmapper 7.sys
start Ligthmapper 8.sys
start Ligthmapper 9.sys
start Ligthmapper 10.sys
start Ligthmapper 11.sys
start Ligthmapper 12.sys
start Ligthmapper 13.sys