AMIDEWINx64.exe /IVN SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /IV  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /ID  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /SM  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /SP  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /SV  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /SS  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /SU  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /SK  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /SF  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /BM  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /BP  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /BV  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /BS  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /BT  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /BLC SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CM  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CT  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CA  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CS  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CV  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CO  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CPC SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CSK SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /CH  SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /PSN SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /PAT SPACEX--%random%-%random%-Spoofer
AMIDEWINx64.exe /PPN SPACEX--%random%-%random%-Spoofer
pause